INSERT INTO FITNESS_CENTER (ADDRESS, EMAIL, IS_DELETED, NAME, PHONE_NUMBER)
VALUES ('Novosadskog sajma 1', 'evelate123@gmail.com', FALSE, 'Evelate', '021258634');
INSERT INTO FITNESS_CENTER (ADDRESS, EMAIL, IS_DELETED, NAME, PHONE_NUMBER)
VALUES ('Micurinova 20', 'micurinova123@gmail.com', FALSE , 'Mind&Muscle', '02146841654');

INSERT INTO USER (ACTIVE, AVERAGE_GRADE, BIRTH, EMAIL, FIRST_NAME, IS_DELETED,  LAST_NAME, PASSWORD, PHONE_NUMBER, ROLE, USERNAME,
                  FITNESS_CENTER_ID)
VALUES (TRUE, 9.45, '2000-07-03', 'blagojevicbodan1@gmail.com', 'Bogdan', FALSE, 'Blagojevic', 'ftn1', '0656549224', 'Admin',
        'bogdan123', 1);
INSERT INTO USER (ACTIVE, AVERAGE_GRADE, BIRTH, EMAIL, FIRST_NAME, IS_DELETED, LAST_NAME, PASSWORD, PHONE_NUMBER, ROLE, USERNAME,
                  FITNESS_CENTER_ID)
VALUES (TRUE, 9.46, '1996-10-27', 'ivana96b@gmail.com', 'Ivana', FALSE, 'Blagojevic', 'ftn2', '0645420909', 'User',
        'ivana123', 1);
INSERT INTO USER (ACTIVE, AVERAGE_GRADE, BIRTH, EMAIL, FIRST_NAME, IS_DELETED, LAST_NAME, PASSWORD, PHONE_NUMBER, ROLE, USERNAME,
                  FITNESS_CENTER_ID)
VALUES (FALSE, 9.13, '1968-8-10', 'zoram68b@gmail.com', 'Zoran', FALSE, 'Blagojevic', 'ftn3', '064512385', 'Trainer',
        'zoran123', 1);
INSERT INTO USER (ACTIVE, AVERAGE_GRADE, BIRTH, EMAIL, FIRST_NAME, IS_DELETED, LAST_NAME, PASSWORD, PHONE_NUMBER, ROLE, USERNAME,
                  FITNESS_CENTER_ID)
VALUES (TRUE, 9.07, '1969-01-02', 'velinka69b@gmail.com', 'Velinka', FALSE, 'Blagojevic', 'ftn4', '0642489285', 'User',
        'velinka123', 2);

INSERT INTO TRAINING (DESCRIPTION, DURATION, NAME, TYPE, TRAINER_ID)
VALUES ('Hard', 45, 'cardio', 'Hit', 1);
INSERT INTO TRAINING (DESCRIPTION, DURATION, NAME, TYPE, TRAINER_ID)
VALUES ('Hit', 45, 'With dumbbels', 'TRX', 2);

INSERT INTO HALL (CAPACITY, IS_DELETED, MARK, FITNESS_CENTER_ID)
VALUES (7, FALSE,'s4', 1);
INSERT INTO HALL (CAPACITY, IS_DELETED, MARK, FITNESS_CENTER_ID)
VALUES (4, FALSE,'s5', 1);
INSERT INTO HALL (CAPACITY, IS_DELETED, MARK, FITNESS_CENTER_ID)
VALUES (5, FALSE ,'s3', 2);
INSERT INTO HALL (CAPACITY, IS_DELETED, MARK, FITNESS_CENTER_ID)
VALUES (16, FALSE ,'s6', 2);

INSERT INTO TERM (NUMBER_OF_APPLICATIONS, PRICE, START, HALL_ID, TRAINER_ID, TRAINING_ID)
VALUES (1, 250, '2021-12-16 12:30', 1, 3, 2);
INSERT INTO TERM (NUMBER_OF_APPLICATIONS, PRICE, START, HALL_ID, TRAINER_ID, TRAINING_ID)
VALUES (1, 200, '2021-12-15 11:30', 2, 1, 1);
INSERT INTO TERM (NUMBER_OF_APPLICATIONS, PRICE, START, HALL_ID, TRAINER_ID, TRAINING_ID)
VALUES (0, 300, '2021-12-16 11:30', 2, 3, 1);
INSERT INTO TERM (NUMBER_OF_APPLICATIONS, PRICE, START, HALL_ID, TRAINER_ID, TRAINING_ID)
VALUES (0, 400, '2021-12-17 11:30', 1, 3, 2);
INSERT INTO TERM (NUMBER_OF_APPLICATIONS, PRICE, START, HALL_ID, TRAINER_ID, TRAINING_ID)
VALUES (0, 350, '2021-07-03 11:30', 1, 3, 2);

INSERT INTO APPLY (DONE, GRADE, IS_DELETED, SPORTS_MAN_ID, TERM_ID)
VALUES (FALSE, 8, FALSE, 2, 1);
INSERT INTO APPLY (DONE, GRADE, IS_DELETED, SPORTS_MAN_ID, TERM_ID)
VALUES (FALSE, 7, FALSE , 2, 2);
