INSERT INTO USER (ACTIVE, AVERAGE_GRADE, BIRTH, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE_NUMBER, ROLE, USERNAME)
VALUES (TRUE, 9.45, '2000-03-7', 'blagojevicbodan1@gmail.com', 'Bogdan', 'Blagojevic', 'ftn1', '0656549224', 'Trainer',
        'bogdan123');
INSERT INTO USER (ACTIVE, AVERAGE_GRADE, BIRTH, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE_NUMBER, ROLE, USERNAME)
VALUES (TRUE, 9.46, '1996-10-27', 'ivana96b@gmail.com', 'Ivana', 'Blagojevic', 'ftn2', '0645420909', 'User',
        'ivana123');

INSERT INTO TRAINING (DESCRIPTION, DURATION, NAME, TYPE, TRAINER_ID)
VALUES ('Hard', 45, 'cardio', 'Hit', 1);

INSERT INTO FITNESS_CENTER (ADDRESS, EMAIL, NAME, PHONE_NUMBER)
VALUES ('Novosadskog sajma 1', 'evelate123@gmail.com', 'Evelate', '021258634');

INSERT INTO HALL (CAPACITY, MARK, FITNESS_CENTER_ID)
VALUES (7, 's4', 1);
INSERT INTO HALL (CAPACITY, MARK, FITNESS_CENTER_ID)
VALUES (5, 's3', 1);

INSERT INTO TERM (PRICE, START, HALL_ID, TRAINER_ID, TRAINING_ID)
VALUES (300, '2021-12-5 12:30:00', 1, 1, 1);

INSERT INTO APPLY (DONE, GRADE, SPORTS_MAN_ID, TERM_ID)
VALUES (TRUE, 8, 1, 1);

INSERT INTO USER_APPLICATIONS (USER_ID, APPLICATIONS_ID)
VALUES (1, 1);

INSERT INTO USER_TRAININGS (USER_ID, TRAININGS_ID)
VALUES (1, 1);

INSERT INTO TRAINING_TERMS (TRAINING_ID, TERMS_ID)
VALUES (1, 1);

INSERT INTO TERM_TERM_APPLY (TERM_ID, TERM_APPLY_ID)
VALUES (1, 1);

INSERT INTO TERM_SPORTS_MAN (TERM_ID, SPORTS_MAN_ID)
VALUES (1, 2);

INSERT INTO HALL_WEEK_SCHEDULE (HALL_ID, WEEK_SCHEDULE_ID)
VALUES (2, 1);

INSERT INTO FITNESS_CENTER_USERS (FITNESS_CENTER_ID, USERS_ID)
VALUES (1, 1);

INSERT INTO FITNESS_CENTER_HALLS (FITNESS_CENTER_ID, HALLS_ID)
VALUES (1, 2);