INSERT INTO FITNESS_CENTER (ADDRESS, EMAIL, NAME, PHONE_NUMBER)
VALUES ('Novosadskog sajma 1', 'evelate123@gmail.com', 'Evelate', '021258634');

INSERT INTO USER (ACTIVE, AVERAGE_GRADE, BIRTH, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE_NUMBER, ROLE, USERNAME,
                  FITNESS_CENTER_ID)
VALUES (TRUE, 9.45, '2000-07-03', 'blagojevicbodan1@gmail.com', 'Bogdan', 'Blagojevic', 'ftn1', '0656549224', 'Trainer',
        'bogdan123', 1);
INSERT INTO USER (ACTIVE, AVERAGE_GRADE, BIRTH, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE_NUMBER, ROLE, USERNAME,
                  FITNESS_CENTER_ID)
VALUES (TRUE, 9.46, '1996-10-27', 'ivana96b@gmail.com', 'Ivana', 'Blagojevic', 'ftn2', '0645420909', 'User',
        'ivana123', 1);

INSERT INTO TRAINING (DESCRIPTION, DURATION, NAME, TYPE, TRAINER_ID)
VALUES ('Hard', 45, 'cardio', 'Hit', 1);

INSERT INTO HALL (CAPACITY, MARK, FITNESS_CENTER_ID)
VALUES (7, 's4', 1);
INSERT INTO HALL (CAPACITY, MARK, FITNESS_CENTER_ID)
VALUES (5, 's3', 1);

INSERT INTO TERM (NUMBER_OF_APPLICATIONS, PRICE, START, HALL_ID, TRAINER_ID, TRAINING_ID)
VALUES (5, 300, '2021-12-5 12:30:00', 1, 1, 1);

INSERT INTO APPLY (DONE, GRADE, SPORTS_MAN_ID, TERM_ID)
VALUES (TRUE, 8, 1, 1);
